### ISSUE TITLE
last major release of mkdirp breaks your package

### ISSUE THREAD

**Issue by szz-dvl** [sydneystockholm/imgr#20]
Getting this error with any version above 1.0.0 of mkdirp:

 ``TypeError: invalid options argument
   at optsArg (/home/szz/myway/bg/node_modules/imgr/node_modules/mkdirp/lib/opts-arg.js:13:11)
   at mkdirp (/home/szz/myway/bg/node_modules/imgr/node_modules/mkdirp/index.js:11:10)
   at exports.Converter.Converter.save (/home/szz/myway/bg/node_modules/imgr/lib/converter.js:156:5)
   at next (/home/szz/myway/bg/node_modules/imgr/lib/utils.js:77:26)
   at exports.Converter.prototype.<computed> (/home/szz/myway/bg/node_modules/imgr/lib/utils.js:79:11)
   at exports.Converter.prototype.<computed> [as save] (/home/szz/myway/bg/node_modules/imgr/lib/utils.js:111:18)
   at handleOriginalStat (/home/szz/myway/bg/node_modules/imgr/lib/server.js:221:14)
   at FSReqCallback.oncomplete (fs.js:167:5)
`
```

Hope it helps,

Szz.

**Comment by StudioLE** [comment]
I've fixed this on a fork of Imgr that adds optional middleware hooks.
https://github.com/StudioLE/imgr/commit/c19b7cd003caa9c26e503e10dbb2145fc09a33ab
Package can be found on NPM: https://www.npmjs.com/package/imgr-le
